### ISSUE TITLE
How to define custom tesseract parameters?

### ISSUE THREAD

**Issue by rortan134** [scribeocr/scribe.js#22]
Such as 
```
await worker.setParameters({
    tessedit_char_whitelist: '0123456789',
  });
```

**Comment by Balearica** [comment]
This currently does not exist, however especially as this project is now linked in the Tesseract.js repo, I agree it should be added.  I will add a way to set Tesseract configs soon.

One general disclaimer is that, even after this is implemented, it's possible that some options that work within Tesseract.js will not work in Scribe.js or behave differently, especially when using the default settings.  This library attempts to improve upon the accuracy provided by Tesseract.js (and does, according to [our benchmark](https://github.com/scribeocr/ocr-benchmark)), and it's possible these changes impact the behavior of some non-default arguments.

**Comment by Balearica** [comment]
I added a `config` option to the `recognize` function that passes arguments to Tesseract.js.  An example of it being used is below.

```js
  await scribe.importFiles([imagePath]);
  await scribe.recognize({
    config: {
      tessedit_char_whitelist: '0123456789',
    },
  });
  const res = await scribe.exportData('text');
  console.log(res);
```

Note that settings will persist between calls to `recognize` until either Tesseract is re-initialized or the setting is changed back.  Therefore, if you only want to set `tessedit_char_whitelist: '0123456789'` for a specific document, you would need to set `tessedit_char_whitelist: ''` for the following document.

**Comment by rortan134** [comment]
Great! Thank you, that was quick
