### ISSUE TITLE
Investigate alternatives to `node-canvas` library

### ISSUE THREAD

**Issue by Balearica** [scribeocr/scribe.js#29]
The primary source of limitations and bug reports on the Node.js version stems from our use of the `node-canvas` library.  We use this library because various features use the Canvas API, which is implemented natively in browser but not Node.js.  We should investigate if any alternative libraries exist.

**Comment by bennyzen** [comment]
What many people (including myself) initially struggle with are the deps needed on the host to get `node-canvas` running. Just looking at their README, there is no direct mention of these vital deps. Looking at the issues there, it becomes pretty obvious that many people are struggling with it. Not being aware that scribe.js uses `node-canvas` under the hood, doesn't make it easier to understand why it's not working.

Just as an example, using a Node v22 container in Docker based on Debian Bookworm, one would need to do something like this in his Dockerfile to get it running: 
```bash
RUN apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
```
It's not that obvious to guess, despite the fact that these deps and package names vary from OS to OS. 

And yes, you're right that it can be a showstopper. Thinking about an alternative, nothing equivalent come to my mind.

**Comment by Balearica** [comment]
Closing as completed.  I replaced `node-canvas` with `canvaskit-wasm` for Node.js users in version `0.6.1`.  This library uses Webassembly rather than relying on a combination of pre-compiled binaries and system libraries (like `node-canvas` does), so I'm hoping this resolves all the platform/system-specific issues.
